[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc= "0.8.24"
optimizer = true
optimizer_runs = 200

[invariant]
runs = 128
depth = 128
fail_on_revert = false
# Increase the number of fuzz runs (default is 256)
fuzz_runs = 500

# Enable persistent storage of failed test cases
fuzz_max_global_rejects = 100000

# To see more logs during testing
verbosity = 3

# Format output as JSON or human-readable
json = false

# Ensures `forge test` captures invariant-style logs
invariant_depth = 100
invariant_runs = 256

remappings = [
  "@chainlink/contracts=lib/chainlink/contracts",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
